apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops 
    spec:
      containers:
      - name: nodeserver
        image: oussemaaaa/devops:latest
        ports:
        - containerPort: 8082
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: devops 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8082
    nodePort: 31110
